[build]
  publish = "dist"
  command = "echo 'Pre-built'"

[[redirects]]
  from = "/:path/"
  to = "/:path"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
