/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ru' | 'de' | 'fr' | 'es' | 'it' | 'nl' | 'ja' | 'zh')
    | ('en' | 'ru' | 'de' | 'fr' | 'es' | 'it' | 'nl' | 'ja' | 'zh')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'ru' | 'de' | 'fr' | 'es' | 'it' | 'nl' | 'ja' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  date: string;
  author?: string | null;
  description?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * e.g. "faq", "partner/eva", "index" for homepage
   */
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  layout?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            buttons?:
              | {
                  label?: string | null;
                  url?: string | null;
                  style?: ('primary' | 'secondary' | 'dotted') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroTextBlock';
          }
        | {
            heading?: string | null;
            slides?:
              | {
                  image?: (number | null) | Media;
                  imageAlt?: string | null;
                  text?: string | null;
                  textColor?: ('white' | 'orange' | 'dark') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sliderBlock';
          }
        | {
            headingLevel?: ('h1' | 'h2' | 'h3') | null;
            heading?: string | null;
            subtext?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            alignment?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSectionBlock';
          }
        | {
            variant?: ('text' | 'icon-colored' | 'with-image') | null;
            columns?:
              | {
                  heading?: string | null;
                  icon?: (number | null) | Media;
                  image?: (number | null) | Media;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnBlock';
          }
        | {
            embedUrl: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            steps?:
              | {
                  stepLabel?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  image?: (number | null) | Media;
                  videoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            heading?: string | null;
            sections?:
              | {
                  sectionTitle?: string | null;
                  questions?:
                    | {
                        question: string;
                        answer: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            variant?: ('grid' | 'diagram') | null;
            diagramImage?: (number | null) | Media;
            specs?:
              | {
                  icon?: (number | null) | Media;
                  label?: string | null;
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specsBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  alt?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            categories?:
              | {
                  label?: string | null;
                  image?: (number | null) | Media;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGridBlock';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  author?: string | null;
                  company?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            plans?:
              | {
                  name?: string | null;
                  price?: string | null;
                  priceNote?: string | null;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  highlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingBlock';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image?: (number | null) | Media;
                  alt?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logosBlock';
          }
        | {
            heading?: string | null;
            requirementsHeading?: string | null;
            requirements?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            downloadHeading?: string | null;
            version?: string | null;
            updatedDate?: string | null;
            language?: string | null;
            downloadUrl?: string | null;
            buttonLabel?: string | null;
            platformImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'downloadBlock';
          }
        | {
            heading?: string | null;
            text?: string | null;
            buttons?:
              | {
                  label?: string | null;
                  url?: string | null;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            heading?: string | null;
            subtext?: string | null;
            embeds?:
              | {
                  embedUrl: string;
                  title?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedGridBlock';
          }
        | {
            /**
             * Paste raw HTML content here. Use for legal pages and other content with complex formatting.
             */
            html?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rawHtmlBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  author?: T;
  description?: T;
  heroImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  layout?:
    | T
    | {
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        heroTextBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sliderBlock?:
          | T
          | {
              heading?: T;
              slides?:
                | T
                | {
                    image?: T;
                    imageAlt?: T;
                    text?: T;
                    textColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSectionBlock?:
          | T
          | {
              headingLevel?: T;
              heading?: T;
              subtext?: T;
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnBlock?:
          | T
          | {
              variant?: T;
              columns?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    image?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              embedUrl?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              steps?:
                | T
                | {
                    stepLabel?: T;
                    content?: T;
                    image?: T;
                    videoUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              heading?: T;
              sections?:
                | T
                | {
                    sectionTitle?: T;
                    questions?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specsBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              variant?: T;
              diagramImage?: T;
              specs?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryGridBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              categories?:
                | T
                | {
                    label?: T;
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    company?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    priceNote?: T;
                    description?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logosBlock?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        downloadBlock?:
          | T
          | {
              heading?: T;
              requirementsHeading?: T;
              requirements?: T;
              downloadHeading?: T;
              version?: T;
              updatedDate?: T;
              language?: T;
              downloadUrl?: T;
              buttonLabel?: T;
              platformImage?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              heading?: T;
              text?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        embedGridBlock?:
          | T
          | {
              heading?: T;
              subtext?: T;
              embeds?:
                | T
                | {
                    embedUrl?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        rawHtmlBlock?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        url: string;
        subItems?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'instagram' | 'twitter' | 'youtube' | 'linkedin') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        subItems?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}